### ISSUE TITLE
Feature: unique identifiers for academic terms

### ISSUE THREAD

**Issue by wrygiel** [erasmus-without-paper/ewp-specs-types-academic-term#1]
Currently, the `<academic-term>` element looks like this:

```xml
<academic-term>
    <academic-year-id>2008/2009</academic-year-id>
    <display-name xml:lang="pl">Semestr letni 2008/2009</display-name>
    <display-name xml:lang="en">Spring semester 2008/2009</display-name>
    <start-date>2009-02-18</start-date>
    <end-date>2009-06-07</end-date>
</academic-term>
```

How can a program automatically identify that this is in fact a spring semester?

Currently, it can look at `<start-date>` and `<end-date>`, and try to match these dates with "spring". This algorithm is not explicit though. We are thinking about adding an (optional) extra element which would help.

### Solution 1

```xml
<academic-term-id>2008/2009-2/2</academic-term-id>
```

The `x/y` suffix indicates that it is the *x-th* term out of *y* terms present in this academic year. E.g.

* `2008/2009-1/1` - the whole academic year,
* `2008/2009-1/2` - the first semester of this academic year (autumn semester),
* `2008/2009-2/2` - the second semester of this academic year (spring semester),
* `2008/2009-1/3` - the first trimester of this academic year,
* etc.

Note, that these identifiers also work on the southern hemisphere, though a bit differently:

* `2008/2008-1/1` - the whole academic year,
* `2008/2008-1/2` - the first semester of this academic year (**spring** :boom: semester),
* `2008/2008-2/2` - the first semester of this academic year (**autumn** :boom: semester),
* `2008/2008-1/4` - the first quadrimester of this academic year,
* etc.

In solution 1 we propose to join this with the (already defined) `academic-year-id`, so that we'll get a unique identifier for the term. This way, we would be able to use this identifier also *outside* of the `<academic-term>` element.

This element would be optional, but recommended. It's worth noting that there MAY exist some weird academic terms, which won't fit in this scheme.

### Solution 2

```xml
<term-number>2/2</term-number>
```

Similar to solution 1, but only the suffix is used, and always in the `<academic-term>` context. In this solution, we are NOT introducing a unique identifier for the academic term, we are only extending the existing `<academic-term>` elements.

### Solution 3

```xml
<academic-year-total-terms>2</academic-year-total-terms>
<academic-year-term-number>2</academic-year-term-number>
```

Same as solution 2, but more verbose (probably *too* verbose).

@erasmus-without-paper/all-members

**Comment by wrygiel** [comment]
> It's worth noting that there MAY exist some weird academic terms, which won't fit in this scheme.

Perhaps we should also discuss if we need to differentiate between "indicating that it's a weird term" and "not providing term ID". If we do, then we would need to introduce some additional extra suffix, e.g. `2008/2009-other` (which would have other meaning than not providing term ID at all).

My personal opinion is that we don't need to differentiate. Also, if we did this, then we could no longer claim that this new datatype might be a "unique term identifier", because there could be many different terms with the same ID (`2008/2009-other`).

**Comment by MartaJuzepczuk** [comment]
All proposed solutions look good to me.

> It's worth noting that there MAY exist some weird academic terms, which won't fit in this scheme.

Is such "weird academic term" still an academic term?

> This element would be optional, but recommended.

> Also, if we did this, then we could no longer claim that this new datatype might be a "unique term identifier", because there could be many different terms with the same ID (2008/2009-other)

If identifier can be empty, it is also a poor identifier (and nonunique). And if this id will not be a real id, maybe it is better to choose simpler solution 2 (or 3)? One more advantage of 2 and 3 is that we don't repeat information about academic year.

**Comment by wrygiel** [comment]
> If identifier can be empty, it is also a poor identifier (and nonunique). And if this id will not be a real id, maybe it is better to choose simpler solution 2 (or 3)?

True. Would be useful to know if other partners also had experience with these "weird terms", and how often such terms occur in practice.

**Comment by kamil-olszewski-uw** [comment]
> > If identifier can be empty, it is also a poor identifier (and nonunique). And if this id will not be a real id, maybe it is better to choose simpler solution 2 (or 3)?

> True. Would be useful to know if other partners also had experience with these "weird terms", and how often such terms occur in practice.

Please note that we should not discuss about "weird terms". We are talking about "weird periods of mobility" that do not match any typical and well known term (year, semester...).

The difference between "other than typical period of mobility" and "period of mobility is missing/not provided" is important.

**Comment by wrygiel** [comment]
> Please note that we should not discuss about "weird terms". We are talking about "weird periods of mobility" that do not match any typical and well known term (year, semester...).

If so, then perhaps we should think about adding new elements to the `<omobility>` element, not the `<academic-term>` element?

**Comment by MartaJuzepczuk** [comment]
Adding id or term number to academic term seems reasonable. But maybe we should move "indicating that it's a weird term" to `omobility` and assume, that every academic term is a "normal" academic term.

**Comment by wrygiel** [comment]
We will continue the "mobility periods" issue here: https://github.com/erasmus-without-paper/ewp-specs-types-academic-term/issues/2

From now on, *this* issue is only about expressing additional information about the *academic term* only (without any connection to the mobility).

**Comment by wrygiel** [comment]
To all interested partners: Please review pull request #3. It contains a fix based on solution 1. If no negative reviews come though, we will release this fix in version `1.1.0`.

**Comment by wrygiel** [comment]
Closed in #3.

**Comment by huntering** [comment]
We think the solution to go for is solution 3. The other solutions are less efficient because they require a new parser while the standard XML parser normally does that work for us. It is harder to understand the XMLSchema because it contains a lot of inline comment. If you want it less verbose, shorten the elementnames (total-terms, term-number) or use attributes. The three fields academic-year, total-terms and term-number should be integers and not strings.

**Comment by wrygiel** [comment]
We went with solution 1 already... (I am leaving the project really soon, so I need to push some decisions without waiting for all partners to comment, sorry about that.)

It is true that it requires some additional parsing, but having a "single string identifier" (instead of having "3-column identifier") is beneficial in many contexts, e.g. when passing academic term identifiers via `x-www-form-urlencoded` parameters:

```
id=2010/2011-1/2&id=2010/2011-2/2&id=2011/2012-1/2
```

Of course, if needed, we could also introduce separate alternatives to be used in other contexts, but usually all three of those will come together, so I think it's beneficial to also keep the (newly introduced) `EwpAcademicTermId` datatype.
