### ISSUE TITLE
Additional way of indicating preliminary mobility periods

### ISSUE THREAD

**Issue by wrygiel** [erasmus-without-paper/ewp-specs-types-academic-term#2]
This issue is the continuation of this thread: https://github.com/erasmus-without-paper/ewp-specs-types-academic-term/issues/1

> > > Please note that we should not discuss about "weird terms". We are talking about "weird periods of mobility" that do not match any typical and well known term (year, semester...).
> > 
> > If so, then perhaps we should think about adding new elements to the `<omobility>` element, not the `<academic-term>` element?
>
> Adding id or term number to academic term seems reasonable. But maybe we should move "indicating that it's a weird term" to `omobility` and assume, that every academic term is a "normal" academic term.

So... if I understood it right, we want a way to indicate if the preliminary mobility's period matches any regular academic term or not. Currently, mobility contains only the `<receiving-academic-year-id>`, which is *required*. We are now talking about adding one or two new *optional* elements besides this one, which would allow the server to indicate some additional conditions. @kamil-olszewski-uw, @MartaJuzepczuk, can you confirm?

### Solution 1 (don't change anything)

This solution assumes that the information we are talking about is equivalent to the information provided in the `<planned-arrival-date>` and `<planned-departure-date>` elements. The client can use these dates to match (more or less) the exact academic term, if it needs to do so.

```xml
<receiving-academic-year-id>2016/2017</receiving-academic-year-id>
<planned-arrival-date>2016-09-01</planned-arrival-date>
<planned-departure-date>2017-01-25</planned-departure-date>
```

The problem with this solution - if I understood correctly - is that these planned dates are defined *much later* than the "preliminary mobility periods" we are now talking about. And these dates are also more "exact", whereas the "preliminary mobility periods" are more vague, and they express things like:

* *the student will arrive during the autumn semester, and **probably will** stay for the entire semester*,
* *the student will arrive during the autumn semester, but **probably won't** stay for the entire semester*,
* *the student will arrive in December 2016 or January 2017, and will stay for 3-5 weeks or so*,
* etc.

@kamil-olszewski-uw, please confirm. I'll try to propose different solutions once I understand the problem exactly.

**Comment by wrygiel** [comment]
BTW, this issue should be started in the "outgoing mobilities" repository. My bad! But let's leave it here, to avoid confusion.

**Comment by kamil-olszewski-uw** [comment]
> @kamil-olszewski-uw, please confirm. I'll try to propose different solutions once I understand the problem exactly.

No, "preliminary mobility periods" do not express anything like that. They simply indicate mobility term with with a possibility of indicating the "other" option.

I would suggest something like that:

```
<xs:element name="student-mobility-for-studies">
...
   <xs:element name="mobility-period" minOccurs="1" maxOccurs="1">
      <xs:choice>
         <xs:element ref="academic-term"/>
         <xs:element name="other">
      </xs:choice>
   </xs:element>
```

**Comment by wrygiel** [comment]
### Solution 2

```xml
<receiving-academic-year-id>2016/2017</receiving-academic-year-id>
<mobility-period> <!-- required or optional? -->
    <receiving-academic-term>...</receiving-academic-term>
    <!-- xor: <other/> -->
</mobility-period>
```

> No, "preliminary mobility periods" do not express anything like that.

Is it possible that they MAY express such things in other databases? It seems that you are catching all non-standard mobility periods in one "catch-all" `other` case, but perhaps other partners would like other options here?

Note, that if we decide to make `<mobility-period>` support only two options, then adding a third one will be backward-incompatible (we will need to introduce a new `<mobility-period2>` replacement in this case, and mark `<mobility-period>` as deprecated). So, we should try to think ahead, and support as many options as it seems reasonable.

**Comment by wrygiel** [comment]
@georgschermann, @BavoNootaert, perhaps you could tell us if you have such "preliminary mobility periods" in your database, and how you express them?

**Comment by wrygiel** [comment]
> Note, that if we decide to make `<mobility-period>` support only two options, then adding a third one will be backward-incompatible (we will need to introduce a new `<mobility-period2>` replacement in this case, and mark `<mobility-period>` as deprecated).

Perhaps I'm wrong here. It might be possible to add new options in a somewhat backward-compatible way, by requiring clients to treat all unknown child elements as `<other/>`.

**Comment by georgschermann** [comment]
We have fields for academic year and semester on the mobility. Initially the planned arrival and departure are set to the start and end date of the chosen academic year / semester and changed later when they get more specific. Beside from this we don't have other standard fields for similar purpose.

**Comment by kamil-olszewski-uw** [comment]
> > No, "preliminary mobility periods" do not express anything like that.

> Is it possible that they MAY express such things in other databases?

Academic year or semester as "prelyminary mobility period" is needed for comparing number of students with quota specified in agreement's conditions, reserve rooms in dormitories and so on. University of Warsaw requires this informations from all partner HEIs. And all partner HEIs never required more detailed information. For example: If receiving HEI had an academic year divided into trimesters, they required from us only the information about the semester, and then they agreed directly with the student in which trimester the student will study.

> It seems that you are catching all non-standard mobility periods in one "catch-all" other case, but perhaps other partners would like other options here?

I don't know. "Other" is rare option for University of Warsaw, used mostly for traineeships and 3rd cycle studies (doctoral studies). Our partner HEIs never required more specific information. We have optional "other - explanation" text field in our system, but we don't share this information with partners.

**Comment by wrygiel** [comment]
> For example: If receiving HEI had an academic year divided into trimesters, they required from us only the information about the semester, and then they agreed directly with the student in which trimester the student will study.

I just realized something. Outgoing Mobilities API is implemented by the sending HEI. The sending HEI doesn't know the exact dates in which academic terms start and end at the receiving HEI. So, it's not possible for the sending to provide `<receiving-academic-term>` element, as I suggested in Solution 2. Is it perhaps more correct to name this `<sending-academic-term>`? This would indicate the academic term at the sending HEI, not the receiving HEI.

> "Other" is rare option for University of Warsaw, used mostly for traineeships and 3rd cycle studies (doctoral studies). Our partner HEIs never required more specific information. We have optional "other - explanation" text field in our system, but we don't share this information with partners.

Perhaps it would be safer to add this explanation to the API (and make it optional). This would allow for such explanations to be automatically generated by such systems, which split the "other" scenario into some separate categories.

### Solution 3

```xml
<receiving-academic-year-id>2016/2017</receiving-academic-year-id>
<mobility-period>
    <sending-academic-term>...</sending-academic-term>
</mobility-period>
```

```xml
<receiving-academic-year-id>2016/2017</receiving-academic-year-id>
<mobility-period>
    <other>
        <explanation xml:lang="en">...</explanation>
        <explanation xml:lang="pl">...</explanation>
    </other>
</mobility-period>
```

**Comment by BavoNootaert** [comment]
Our mobilities contain academic year, expected and effective arrival and departure dates, and semester (first, second or both). All are required.

**Comment by wrygiel** [comment]
### Solution 4

Make use of the [newly introduced](https://github.com/erasmus-without-paper/ewp-specs-types-academic-term/blob/v1.1.0/CHANGELOG.md) `EwpAcademicTermId` type. Provide only the identifier, instead of providing the entire description of the term. Make this new element optional. No "other" option is present in this solution, but perhaps clients may simply assume that a missing `<sending-academic-term-id>` means "other"?

```xml
<receiving-academic-year-id>2016/2017</receiving-academic-year-id>
<sending-academic-term-ewp-id>2016/2017-1/2</sending-academic-term-ewp-id>
```

**Comment by wrygiel** [comment]
### Solution 5

Same as solution 4, but we force the sender to output exactly one: `<sending-academic-term-ewp-id>` or `<non-standard-mobility-period/>`.

Currently `<non-standard-mobility-period/>` will be empty (no explanation element, etc.). Perhaps we will add extra elements in the future.

**Comment by wrygiel** [comment]
@erasmus-without-paper/all-members To all interested parties - please review this PR: https://github.com/erasmus-without-paper/ewp-specs-api-omobilities/pull/30 (based on Solution 5)

I plan to merge it tomorrow.
