### ISSUE TITLE
Let's include the other values from the data model

### ISSUE THREAD

**Issue by lennertVanSever** [erasmus-without-paper/ewp-specs-types-academic-term#6]
<img width="432" alt="screen shot 2018-04-03 at 16 13 20" src="https://user-images.githubusercontent.com/23064517/38254599-fadcf0bc-3759-11e8-8e87-6e7fbb93e5d0.png">
In this screenshot from the EWP data model you can see that other values are defined that don't exist in the schema or example. So let's introduce the following values:

- Application deadline
- Nomination deadline
- Arrival date
- Start exam date

**Comment by kamil-olszewski-uw** [comment]
[EWP data model](https://github.com/erasmus-without-paper/ewp-wp3-data-model) is a snapshot from early stage of the project. It served as basis for the schema/API creation, but the schema includes some changes resulting from many technical and business discussions. Therefore, data model in its current form can't be used as a source for implementation. Maybe it should be updated.

In our opinion, the fields you have mentioned destroy the context-free nature of the academic term object and are unnecessary and/or difficult to implement in current form. For example: There may be many nomination deadlines, each for every study cycle (bachelor studies, doctoral studies...). And those deadlines are often defined one or two months before deadline date. In many cases deadlines are not even stored in sending HEIs' databases.

Project partners never asked for these fields in the schema.

Of course, we invite all partners to submit substantiated proposals for new fields and other changes in the future major APIs' versions.

**Comment by lennertVanSever** [comment]
I certainly agree that the EWP data model should be updated so that it at least reflects the latest updates. I think many developers (like me) like to work with the ERD of the EWP to have a complete overview of the data structure. Who makes the final decision which values from the data model are not implemented in the schemas?

**Comment by janinamincer-daszkiewicz** [comment]
The group :)
Those who do not take part in the discussion do not have the influence.

**Comment by lennertVanSever** [comment]
Okay, clear. 
I'm currently working on a project where the application deadline, nomination deadline, arrival date and start exam date are relevant. I think in general that this data is essential for students. If it is only relevant when it's attached to a study cycle then we should change the model so that this is the case.

**Comment by janinamincer-daszkiewicz** [comment]
This is definitely something to be discussed.
Generally EWP is for administration. One of our problems is that in various databases various types of data are stored and are obligatory. It is difficult to get consensus. Quite often data obligatory in one HEI are missing or optional in the other.

**Comment by georgschermann** [comment]
As far as I remember, the Academic Terms were left out because the scope of EWP got too big.
And the Data Model was never ment to be fully covered by the APIs. There are a lot of other useful infomation which is currently not exchanged via APIs.
