### ISSUE TITLE
Is stable-v2 considered stable?

### ISSUE THREAD

**Issue by j-be** [erasmus-without-paper/ewp-specs-types-academic-term#8]
As far as I can tell, `stable-v2` is released and supposed to supersede `stable-v1`, but:

* default branch of this repo is still `stable-v1`
* release tag is missing
* nothing in `CHANGELOG.md` regarding the changes

So I wonder if it is actually stable, or not.

**Comment by mkurzydlowski** [comment]
We have released version 2.0.0 just now.
